package uk.gov.justice.laa.bulk.claim.mapper;

import static org.junit.jupiter.api.Assertions.assertEquals;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;
import lombok.extern.slf4j.Slf4j;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import uk.gov.justice.laa.bulk.claim.model.BulkClaimMatterStarts;
import uk.gov.justice.laa.bulk.claim.model.BulkClaimOffice;
import uk.gov.justice.laa.bulk.claim.model.BulkClaimOutcome;
import uk.gov.justice.laa.bulk.claim.model.BulkClaimSchedule;
import uk.gov.justice.laa.bulk.claim.model.BulkClaimSubmission;
import uk.gov.justice.laa.bulk.claim.model.FileSubmission;
import uk.gov.justice.laa.bulk.claim.model.csv.CsvMatterStarts;
import uk.gov.justice.laa.bulk.claim.model.csv.CsvOffice;
import uk.gov.justice.laa.bulk.claim.model.csv.CsvOutcome;
import uk.gov.justice.laa.bulk.claim.model.csv.CsvSchedule;
import uk.gov.justice.laa.bulk.claim.model.csv.CsvSubmission;
import uk.gov.justice.laa.bulk.claim.model.xml.XmlOffice;
import uk.gov.justice.laa.bulk.claim.model.xml.XmlOutcome;
import uk.gov.justice.laa.bulk.claim.model.xml.XmlSchedule;
import uk.gov.justice.laa.bulk.claim.model.xml.XmlSubmission;

@Slf4j
public class BulkClaimMapperTests {

  private final BulkClaimSubmissionMapper bulkClaimMapper = new BulkClaimSubmissionMapperImpl();

  @Test
  @DisplayName("Should map csv submission to bulk claim submission")
  void shouldMapCsvSubmissionToBulkClaimSubmission() {
    FileSubmission submission =
        new CsvSubmission(
            new CsvOffice("account"),
            new CsvSchedule("submissionPeriod", "areaOfLaw", "scheduleNum"),
            List.of(
                new CsvOutcome(
                    "matterType",
                    "feeCode",
                    "caseRefNumber",
                    "01/01/2000",
                    "caseId",
                    "caseStageLevel",
                    "ufn",
                    "procurementArea",
                    "accessPoint",
                    "clientForename",
                    "clientSurname",
                    "02/01/2000",
                    "ucn",
                    "claRefNumber",
                    "claExemption",
                    "gender",
                    "ethnicity",
                    "disability",
                    "clientPostCode",
                    "03/01/2000",
                    "1",
                    "2",
                    "3",
                    "0.01",
                    "0.02",
                    "0.03",
                    "0.04",
                    "0.05",
                    "0.06",
                    "Y",
                    "N",
                    "clientType",
                    "Y",
                    "0.07",
                    "outcomeCode",
                    "N",
                    "claimType",
                    "0.08",
                    "typeOfAdvice",
                    "Y",
                    "scheduleRef",
                    "cmrhOral",
                    "cmrhTelephone",
                    "aitHearingCentre",
                    "N",
                    "hoInterview",
                    "hoUcn",
                    "04/01/2000",
                    "0.09",
                    "deliveryLocation",
                    "priorAuthorityRef",
                    "jrFormFilling",
                    "Y",
                    "meetingsAttended",
                    "4",
                    "5",
                    "mhtRefNumber",
                    "stageReached",
                    "followOnWork",
                    "nationalRefMechanismAdvice",
                    "exemptionCriteriaSatisfied",
                    "exclCaseFundingRef",
                    "6",
                    "7",
                    "ircSurgery",
                    "05/01/2000",
                    "lineNumber",
                    "crimeMatterType",
                    "feeScheme",
                    "06/01/2000",
                    "8",
                    "9",
                    "policeStation",
                    "dsccNumber",
                    "maatId",
                    "prisonLawPriorApproval",
                    "dutySolicitor",
                    "youthCourt",
                    "schemeId",
                    "10",
                    "11",
                    "outreach",
                    "referral",
                    "clientLegallyAided",
                    "client2Forename",
                    "client2Surname",
                    "07/01/2000",
                    "client2Ucn",
                    "client2PostCode",
                    "client2Gender",
                    "client2Ethnicity",
                    "client2Disability",
                    "client2LegallyAided",
                    "uniqueCaseId",
                    "standardFeeCat",
                    "client2PostalApplAccp",
                    "costsDamagesRecovered",
                    "eligibleClient",
                    "courtLocation",
                    "localAuthorityNumber",
                    "paNumber",
                    "0.10",
                    "08/01/2000")),
            List.of(
                new CsvMatterStarts(
                    "scheduleRef",
                    "procurementArea",
                    "accessPoint",
                    "mat",
                    "immas",
                    "categoryCode",
                    "deliveryLocation")));

    BulkClaimSubmission expected = getExpectedBulkClaimSubmission(true);

    BulkClaimSubmission actual = bulkClaimMapper.toBulkClaimSubmission(submission);

    assertEquals(expected, actual);
  }

  @Test
  @DisplayName("Should map xml submission to bulk claim submission")
  void shouldMapXmlSubmissionToBulkClaimSubmission() {
    FileSubmission submission =
        new XmlSubmission(
            null,
            new XmlOffice(
                "account",
                new XmlSchedule(
                    "submissionPeriod",
                    "areaOfLaw",
                    "scheduleNum",
                    List.of(
                        new XmlOutcome(
                            "matterType",
                            "feeCode",
                            "caseRefNumber",
                            "01/01/2000",
                            "caseId",
                            "caseStageLevel",
                            "ufn",
                            "procurementArea",
                            "accessPoint",
                            "clientForename",
                            "clientSurname",
                            "02/01/2000",
                            "ucn",
                            "claRefNumber",
                            "claExemption",
                            "gender",
                            "ethnicity",
                            "disability",
                            "clientPostCode",
                            "03/01/2000",
                            "1",
                            "2",
                            "3",
                            "0.01",
                            "0.02",
                            "0.03",
                            "0.04",
                            "0.05",
                            "0.06",
                            "Y",
                            "N",
                            "clientType",
                            "Y",
                            "0.07",
                            "outcomeCode",
                            "N",
                            "claimType",
                            "0.08",
                            "typeOfAdvice",
                            "Y",
                            "scheduleRef",
                            "cmrhOral",
                            "cmrhTelephone",
                            "aitHearingCentre",
                            "N",
                            "hoInterview",
                            "hoUcn",
                            "04/01/2000",
                            "0.09",
                            "deliveryLocation",
                            "priorAuthorityRef",
                            "jrFormFilling",
                            "Y",
                            "meetingsAttended",
                            "4",
                            "5",
                            "mhtRefNumber",
                            "stageReached",
                            "followOnWork",
                            "nationalRefMechanismAdvice",
                            "exemptionCriteriaSatisfied",
                            "exclCaseFundingRef",
                            "6",
                            "7",
                            "ircSurgery",
                            "05/01/2000",
                            "lineNumber",
                            "crimeMatterType",
                            "feeScheme",
                            "06/01/2000",
                            "8",
                            "9",
                            "policeStation",
                            "dsccNumber",
                            "maatId",
                            "prisonLawPriorApproval",
                            "dutySolicitor",
                            "youthCourt",
                            "schemeId",
                            "10",
                            "11",
                            "outreach",
                            "referral",
                            "clientLegallyAided",
                            "client2Forename",
                            "client2Surname",
                            "07/01/2000",
                            "client2Ucn",
                            "client2PostCode",
                            "client2Gender",
                            "client2Ethnicity",
                            "client2Disability",
                            "client2LegallyAided",
                            "uniqueCaseId",
                            "standardFeeCat",
                            "client2PostalApplAccp",
                            "costsDamagesRecovered",
                            "eligibleClient",
                            "courtLocation",
                            "localAuthorityNumber",
                            "paNumber",
                            "0.10",
                            "08/01/2000")))));

    BulkClaimSubmission expected = getExpectedBulkClaimSubmission(false);

    BulkClaimSubmission actual = bulkClaimMapper.toBulkClaimSubmission(submission);

    assertEquals(expected, actual);
  }

  private BulkClaimSubmission getExpectedBulkClaimSubmission(boolean includeMatterStarts) {
    List<BulkClaimMatterStarts> matterStarts =
        Boolean.TRUE.equals(includeMatterStarts)
            ? List.of(
                new BulkClaimMatterStarts(
                    "scheduleRef",
                    "procurementArea",
                    "accessPoint",
                    "mat",
                    "immas",
                    "categoryCode",
                    "deliveryLocation"))
            : List.of();

    return new BulkClaimSubmission(
        new BulkClaimOffice("account"),
        new BulkClaimSchedule("submissionPeriod", "areaOfLaw", "scheduleNum"),
        List.of(
            new BulkClaimOutcome(
                "matterType",
                "feeCode",
                "caseRefNumber",
                LocalDate.of(2000, 1, 1),
                "caseId",
                "caseStageLevel",
                "ufn",
                "procurementArea",
                "accessPoint",
                "clientForename",
                "clientSurname",
                LocalDate.of(2000, 1, 2),
                "ucn",
                "claRefNumber",
                "claExemption",
                "gender",
                "ethnicity",
                "disability",
                "clientPostCode",
                LocalDate.of(2000, 1, 3),
                1,
                2,
                3,
                new BigDecimal("0.01"),
                new BigDecimal("0.02"),
                new BigDecimal("0.03"),
                new BigDecimal("0.04"),
                new BigDecimal("0.05"),
                new BigDecimal("0.06"),
                Boolean.TRUE,
                Boolean.FALSE,
                "clientType",
                Boolean.TRUE,
                new BigDecimal("0.07"),
                "outcomeCode",
                Boolean.FALSE,
                "claimType",
                new BigDecimal("0.08"),
                "typeOfAdvice",
                Boolean.TRUE,
                "scheduleRef",
                "cmrhOral",
                "cmrhTelephone",
                "aitHearingCentre",
                Boolean.FALSE,
                "hoInterview",
                "hoUcn",
                LocalDate.of(2000, 1, 4),
                new BigDecimal("0.09"),
                "deliveryLocation",
                "priorAuthorityRef",
                "jrFormFilling",
                Boolean.TRUE,
                "meetingsAttended",
                4,
                5,
                "mhtRefNumber",
                "stageReached",
                "followOnWork",
                "nationalRefMechanismAdvice",
                "exemptionCriteriaSatisfied",
                "exclCaseFundingRef",
                6,
                7,
                "ircSurgery",
                LocalDate.of(2000, 1, 5),
                "lineNumber",
                "crimeMatterType",
                "feeScheme",
                LocalDate.of(2000, 1, 6),
                8,
                9,
                "policeStation",
                "dsccNumber",
                "maatId",
                "prisonLawPriorApproval",
                "dutySolicitor",
                "youthCourt",
                "schemeId",
                10,
                11,
                "outreach",
                "referral",
                "clientLegallyAided",
                "client2Forename",
                "client2Surname",
                LocalDate.of(2000, 1, 7),
                "client2Ucn",
                "client2PostCode",
                "client2Gender",
                "client2Ethnicity",
                "client2Disability",
                "client2LegallyAided",
                "uniqueCaseId",
                "standardFeeCat",
                "client2PostalApplAccp",
                "costsDamagesRecovered",
                "eligibleClient",
                "courtLocation",
                "localAuthorityNumber",
                "paNumber",
                new BigDecimal("0.10"),
                LocalDate.of(2000, 1, 8))),
        matterStarts);
  }
}
