laa:
  bulk-claim-queue:
    name: test-queue-name
  dstew:
    payments:
      validator:
        submission:
          minimum-period: APR-2025
spring:
  cloud:
    aws:
      region:
        static: us-east-1

resilience4j.retry:
  instances:
    pdaRetry:
      maxAttempts: 3
      waitDuration: 500ms
      retry-exceptions:
        - java.lang.RuntimeException
