laa:
  provider-details-api:
    host: http://localhost:8192
    url: ${laa.provider-details-api.host}
    accessToken: 123
  claims-api:
    host: http://localhost:8190
    url: ${laa.claims-api.host}
    accessToken: 123
  fee-scheme-platform-api:
    host: http://localhost:8191
    url: ${laa.claims-api.host}
    accessToken: 123
  bulk-claim-queue:
    name: claims-api-queue

spring:
  cloud:
    aws:
      credentials:
        access-key: "dummy-access-key"
        secret-key: "dummy-secret-key"
      region:
        static: "us-east-1"
      sqs:
        endpoint: "http://localhost:4566"