name: Helm deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
      claim_api_environment_name:
        required: true
        type: string
        description: The name of the environment which Claims API is deployed to
      image_tag:
        required: true
        type: string

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set branch name
        run: echo "GIT_BRANCH=${GITHUB_HEAD_REF:-${GITHUB_REF_NAME}}" >> $GITHUB_ENV

      - name: Can I deploy?
        id: can-i-deploy
        uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/pact-can-i-deploy@dc4173bfc12f714d7e8cbdd9f524d00ef02e25c4 # v2.1.1
        with:
          pacticipant: 'laa-data-claims-event-service'
          environment: ${{ inputs.claim_api_environment_name }}
          pact_broker_url: 'https://laa-data-pact-broker.apps.live.cloud-platform.service.justice.gov.uk/'
          pact_broker_username: ${{ secrets.pact_broker_username }}
          pact_broker_password: ${{ secrets.pact_broker_password }}

      - name: Authenticate to the cluster
        run: |
          echo "${{ secrets.kube_cert }}" > ca.crt
          kubectl config set-cluster ${{ secrets.KUBE_CLUSTER }} --certificate-authority=./ca.crt --server=https://${{ secrets.KUBE_CLUSTER }}
          kubectl config set-credentials deploy-user --token=${{ secrets.KUBE_TOKEN }}
          kubectl config set-context ${{ secrets.KUBE_CLUSTER }} --cluster=${{ secrets.KUBE_CLUSTER }} --user=deploy-user --namespace=${{ secrets.KUBE_NAMESPACE }}
          kubectl config use-context ${{ secrets.KUBE_CLUSTER }}

      - name: Configure aws credentials
        uses: aws-actions/configure-aws-credentials@ec61189d14ec14c8efccab744f656cffd0e33f37 # v6
        with:
          role-to-assume: ${{ secrets.LAA_DATA_CLAIMS_EVENT_SERVICE_ECR_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.LAA_DATA_CLAIMS_EVENT_SERVICE_ECR_REGION }}

      - name: Login ecr
        uses: aws-actions/amazon-ecr-login@376925c9d111252e87ae59691e5a442dd100ef6a # v2.1.3
        id: login-ecr

      - name: Set helm chart app version
        env:
          IMAGE_TAG: ${{ inputs.image_tag }}
        run: |
          # use env var to avoid injecting github context directly into the shell
          yq eval-all "( .appVersion = \"$IMAGE_TAG\" )" -i helm-chart/Chart.yaml
          cat helm-chart/Chart.yaml

      - name: Install or upgrade helm charts
        id: helm-install
        env:
          DEPLOYMENT_NAME: ${{ inputs.deployment_name }}
          ENV_VALUES_FILE: "helm-chart/values/env-${{ inputs.environment }}.yaml"
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: ${{ vars.LAA_DATA_CLAIMS_EVENT_SERVICE_ECR_REPOSITORY }}
        run: |
          echo "Deploying Helm release '$DEPLOYMENT_NAME'..."
          helm upgrade --install --wait --timeout 5m \
            -f "$ENV_VALUES_FILE" \
            "$DEPLOYMENT_NAME" helm-chart \
            --set image.repository="$REGISTRY/$REPOSITORY"

          REG_REPO="$REGISTRY/$REPOSITORY"
          IMAGES=$(helm get manifest "$DEPLOYMENT_NAME" | yq -o=json '.' | jq -sc --arg registry "$REG_REPO" '[.[] | select(.kind == "Deployment") | select(.spec.template.spec.containers[0].image | contains($registry)) | {image_version_tag: .metadata.labels.appVersion, release_tag: .metadata.name}]')

          echo "images=$IMAGES" >> $GITHUB_OUTPUT
          echo "Deployed Images: $(echo "$IMAGES" | jq)"

      - name: Record deployment to pact broker
        id: record-deployment-to-pact-broker
        uses: ministryofjustice/laa-ccms-common-workflows/.github/actions/pact-record-deployment@dc4173bfc12f714d7e8cbdd9f524d00ef02e25c4 # v2.1.1
        with:
          pacticipant: 'laa-data-claims-event-service'
          environment: ${{ inputs.claim_api_environment_name }}
          pact_broker_url: 'https://laa-data-pact-broker.apps.live.cloud-platform.service.justice.gov.uk/'
          pact_broker_username: ${{ secrets.pact_broker_username }}
          pact_broker_password: ${{ secrets.pact_broker_password }}
